version: '3'
services:
  master:
    image: mysql:latest
    container_name: db_master
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_prisma
    ports:
      - 9090:3306
  slave:
    image: mysql:latest
    container_name: db_slave
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_prisma
    ports:
      - 9091:3306
    command: mysqld --server-id=2 --log-bin=mysql-bin --relay-log=slave-relay-bin --log-slave-updates=1 --auto-increment-offset=1 --auto-increment-increment=2 --master-info-repository=TABLE --relay-log-info-repository=TABLE --replicate-do-db=db_prisma --relay-log-recovery=1