-- CreateTable
CREATE TABLE `Usuario` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `USUARIO` VARCHAR(191) NOT NULL,
    `SENHA` VARCHAR(191) NOT NULL,
    `CPF` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,
    `ENDERECO` VARCHAR(191) NOT NULL,
    `NUMERO` INTEGER NULL,
    `BAIRRO` VARCHAR(191) NOT NULL,
    `CIDADE` VARCHAR(191) NOT NULL,
    `UF` VARCHAR(191) NOT NULL,
    `CEP` VARCHAR(191) NOT NULL,
    `FONE` VARCHAR(191) NOT NULL,
    `IS_ADM` BOOLEAN NOT NULL DEFAULT false,
    `ULTIMO_ACESSO` DATETIME(3) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Produto` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `DESCRICAO` VARCHAR(191) NULL,
    `PRECO` DOUBLE NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pedido` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USUARIO_ID` INTEGER NOT NULL,
    `DT_INCLUSAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DT_ALTERACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VLR_TOTAL` DOUBLE NOT NULL,
    `STATUS` ENUM('PENDENTE', 'PAGO', 'FINALIZADO') NOT NULL DEFAULT 'PENDENTE',

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Carrinho` (
    `PEDIDO_ID` INTEGER NOT NULL,
    `PRODUTO_ID` INTEGER NOT NULL,
    `QTDE` INTEGER NOT NULL,
    `VLR_UNITARIO` DOUBLE NOT NULL,

    PRIMARY KEY (`PEDIDO_ID`, `PRODUTO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Pedido` ADD CONSTRAINT `Pedido_USUARIO_ID_fkey` FOREIGN KEY (`USUARIO_ID`) REFERENCES `Usuario`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Carrinho` ADD CONSTRAINT `Carrinho_PEDIDO_ID_fkey` FOREIGN KEY (`PEDIDO_ID`) REFERENCES `Pedido`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Carrinho` ADD CONSTRAINT `Carrinho_PRODUTO_ID_fkey` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `Produto`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
